# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core
# Add steps that runs thest, create a NuGet pachage, deploy and mor:
# si algo, revise docs de microsoft/devops/pipelines/laguages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps: 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'